config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#index", as: "home"
  # articles
  get "/posts", as: "posts_format", to: "posts#index"
  get "/post/:id", to: "posts#show"
  get "/article/:slug", to: "pages#show", as: "post_show"
  # comments
  post "/comment/new", to: "comments#create", as: "create_comment"
  get "/comment/:id/delete", as: "delete_comment", to: "comments#destroy"
  #user
  get "/user/:username", to: "users#show", as: "show_user"
  get "/connexion", to: "connect#index_login", as: "login"
  post "/connexion", to: "connect#login"
  #categories
  get "categorie/:name", to: "categories#show", as: "show_category"
  #others
  post "/nous-contactez", to: "contact#index", as: "footer_mail"
  get "/404", :to => "pages#index"
  get "/recherche", as: "search", to: "pages#search"
  get "/rss", as: 'rss', to: "rss#index"

  # administration
  scope "/admin" do
    get "/", as: "admin_home", to: "admin#index"
    post "/", as: "new_post", to: "posts#create"
    get "/commentaires", as: "comments_management", to: "admin#manage_comments"
    get "/all_comments", as: "all_comments", to: "admin#all_comments"
    get "/ninja/:id", as: "ninja", to: "admin#ninja"
    get "/users", as: "users_management", to: "admin#manage_users"
    get "/categories", as: "categories_management", to: "admin#manage_categories"
    get "/categories/:id/destroy", as: "categories_destroy", to: "categories#destroy"
  end

  # user profile
  scope "/profil" do
    get "/", as: "user_profile", to: "profiles#dashboard"
    get "/deconextion", as: "disconnect", to: "profiles#disconnect"
    get "/article/:id/edit", as: "edit_article", to: "profiles#edit_post"
    post "/article/edit/:id", as: "edit", to: "posts#edit"
    get "/article/:id/delete", as: "delete", to: "posts#destroy"
  end

end

app/controllers/profiles_controller.rb
=begin
* Controlleur gérant la gestion du profile de l'utilisateur
=end

class ProfilesController < ApplicationController

  include AdminHelper
  before_action :protection

  def dashboard
    render layout: "layouts/main"
  end

  def edit_post
    user = User.find(session[:id])
    post = Post.find(params[:id])
    if post && user && is_connect_and_admin?
      if post.user_id == user.id
        @post = post
        render :layout => "layouts/main"
      else
        redirect_to home_path
      end
    else
      redirect_to home_path
    end
  end

  def disconnect
    reset_session
    flash[:msg] = "Vous avez bien été déconnecté"
    redirect_to admin_home_path
  end

  private
  def protection
    if is_connect?
      @user = User.find(session[:id])
    else
      redirect_to home_path
    end
  end

end

app/views/profiles/dashboard.html.erb
<% content_for :content do %>

  <div class="profile-picture" style="width: 100%;display: flex;justify-content: center;">
    <img src="<%= @user.picture %>" alt="" class="img-circle" style="width: 100px;height: 100px;background: #fff;overflow: hidden;box-shadow: 0 0 5px #ebebeb;border: 3px solid #00aeef">
  </div>
  <div style="width: 100%;display: flex;justify-content: center">
    <h3><%= @user.username %></h3>
  </div>
  <div style="width: 100%;display: flex;justify-content: center">
    <a href="<%= disconnect_path %>" class="btn btn-default">Déconnexion</a>
  </div>
  <% if flash[:msg] %>
    <div style="margin-top: 20px;" class="alert alert-success"><%= flash[:msg] %></div>
  <% end %>
  <h1>Mon profil</h1>
  <table class="table table-hover" style="margin: 40px 0;">
    <thead>
    <tr>
      <th scope="col">Nom d'utilisateur</th>
      <th scope="col">Email</th>
      <th scope="col">Inscrit le </th>
      <th scope="col">Dernière modification du profil</th>
      <th scope="col">Articles postés</th>
      <th scope="col">Commentaires postés</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <th><%= @user.username %></th>
      <td><%= @user.email %></td>
      <td><%= @user.created_at %></td>
      <td><%= @user.updated_at %></td>
      <td><%= @user.post.count %></td>
      <td><%= @user.comment.count %></td>
    </tr>
    </tbody>
  </table>

  <% if is_connect_and_admin? %>
    <% if is_banned? %>
      <div class="alert alert-warning">Vous avez été bannis. Vous ne pouvez donc malheureusement ne plus écrire d'articles..</div>
    <% else %>
      <h1>Mes derniers articles</h1>
      <a href="<%= admin_home_path %>" data-turbolinks="false" class="btn btn-success">Nouvel article</a>
      <% if is_connect_and_superadmin? %>
        <a href="<%= comments_management_path %>" data-turbolinks="false" id="comments-button" class="btn btn-success">Gérer les commentaires</a>
        <a href="<%= users_management_path %>" data-turbolinks="true" id="users-button" class="btn btn-success">Gérer les utilisateurs</a>
        <a href="<%= categories_management_path %>" data-turbolinks="true" id="users-button" class="btn btn-success">Gérer les catégories</a>
      <% end %>
      <% if @user.post.count < 1 %>
        <div style="margin: 30px 0;" class="alert alert-warning">Vous avez aucun article posté. Cliquez sur le bouton nouvel article afn d'en écrire un.</div>
      <% else %>
        <table class="table table-hover" style="margin: 40px 0;">
          <thead>
          <tr>
            <th scope="col">Titre</th>
            <th scope="col">Posté le </th>
            <th scope="col">Dernière modification le</th>
            <th scope="col">Commentaires postés</th>
            <th scope="col">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @user.post.order("created_at DESC").each do |post| %>
            <tr>
              <th><a target="_blank" href="<%= post_show_path(post.slug) %>"><%= post.title %> </a><%= raw !post.is_posted ? "<span style='color: green;font-style: italic;'>(Brouillon)</span>" : "" %></th>
              <td><%= post.created_at %></td>
              <td><%= post.updated_at %></td>
              <td><%= post.comment.count %></td>
              <td><a data-turbolinks="false" href="<%= edit_article_path(post.id) %>" class="btn btn-primary">Éditer</a></td>
              <td><a href="<%= delete_path(post.id) %>" class="btn btn-danger" id="delete-post">Suprimer</a></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/profiles/edit_post.html.erb
<% content_for :content do %>

  <a href="<%= user_profile_path %>">Retour</a>
  <h1>Édition de l'article <strong><%= @post.title %></strong></h1>
  <div class="alert alert-warning">Vous êtes en mode édition</div>
  <% if !@post.is_posted %>
    <div class="alert alert-info">Cet article est en mode brouillon</div>
  <% end %>
  <form action="<%= edit_path(@post.id) %>" method="post" style="margin-bottom: 40px;">
    <div class="form-group">
      <label for="posted">Brouillon</label>
      <input type="checkbox" name="is_posted" <%= @post.is_posted ? "not" : "checked='checked'" %>>
    </div>  
    <div class="form-group">
      <label>Titre de l'article</label>
      <input type="text" class="form-control" name="title" placeholder="Mon titre..." value="<%= @post.title %>">
    </div>
    <div class="form-group">
      <label>Slug de l'article</label>
      <input type="text" class="form-control" name="slug" placeholder="mon-slug" value="<%= @post.slug %>">
    </div>
    <div class="form-group">
      <label>Miniature de l'article</label>
      <input type="text" class="form-control" name="thumbnail" placeholder="Miniature" value="<%= @post.thumbnail %>">
    </div>
    <div class="form-group">
      <label>Catégorie</label>
      <select name="category" class="form-control">
        <option selected="selected" value="<%= @post.category.id %>"><%= @post.category.name %></option>
        <% Category.where.not(name: @post.category.name).each do |c| %>
          <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>

    <input type="hidden" name="post" value="<%= @post.id %>">

    <div class="form-group">
      <label>Contenu</label>
      <textarea name="content" class="form-control" cols="30" rows="10" id="markdown-textarea" placeholder="Contenu de l'article.."><%= @post.content %></textarea>
    </div>

    <button type="submit" class="btn btn-default">Modifier</button>

  </form>

<% end %>