config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#index", as: "home"
  # articles
  get "/posts", as: "posts_format", to: "posts#index"
  get "/post/:id", to: "posts#show"
  get "/article/:slug", to: "pages#show", as: "post_show"
  # comments
  post "/comment/new", to: "comments#create", as: "create_comment"
  get "/comment/:id/delete", as: "delete_comment", to: "comments#destroy"
  #user
  get "/user/:username", to: "users#show", as: "show_user"
  get "/connexion", to: "connect#index_login", as: "login"
  post "/connexion", to: "connect#login"
  #categories
  get "categorie/:name", to: "categories#show", as: "show_category"
  #others
  post "/nous-contactez", to: "contact#index", as: "footer_mail"
  get "/404", :to => "pages#index"
  get "/recherche", as: "search", to: "pages#search"
  get "/rss", as: 'rss', to: "rss#index"

  # administration
  scope "/admin" do
    get "/", as: "admin_home", to: "admin#index"
    post "/", as: "new_post", to: "posts#create"
    get "/commentaires", as: "comments_management", to: "admin#manage_comments"
    get "/all_comments", as: "all_comments", to: "admin#all_comments"
    get "/ninja/:id", as: "ninja", to: "admin#ninja"
    get "/users", as: "users_management", to: "admin#manage_users"
    get "/categories", as: "categories_management", to: "admin#manage_categories"
    get "/categories/:id/destroy", as: "categories_destroy", to: "categories#destroy"
  end

  # user profile
  scope "/profil" do
    get "/", as: "user_profile", to: "profiles#dashboard"
    get "/deconextion", as: "disconnect", to: "profiles#disconnect"
    get "/article/:id/edit", as: "edit_article", to: "profiles#edit_post"
    post "/article/edit/:id", as: "edit", to: "posts#edit"
    get "/article/:id/delete", as: "delete", to: "posts#destroy"
  end

end

app/views/admin/index.html.erb
<% content_for :content do %>

  <div class="alert alert-warning">Vous êtes en mode de création d'article</div>
  <% if flash[:error] %>

    <div class="alert alert-danger">
      <ul>
        <% flash[:error].each do |e| %>
        <li>- <%= e %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <form action="<%= new_post_path %>" method="post" style="margin-bottom: 40px;" id="new-post-form" data-url="<%= admin_home_path %>">
    <div class="form-group">
      <label>Titre de l'article</label>
      <input type="text" class="form-control" name="title" placeholder="Mon titre..." id="title">
    </div>
    <div class="form-group">
      <label>Slug de l'article</label>
      <input type="text" id="slug" class="form-control" name="slug" placeholder="mon-slug">
    </div>
    <div class="form-group">
      <label>Miniature de l'article</label>
      <input type="text" class="form-control" name="thumbnail" placeholder="Miniature">
    </div>
    <div class="form-group">
      <label>Catégorie</label>
      <select name="category" class="form-control">
        <option selected="selected">Catégorie</option>
        <% Category.all.each do |c| %>
          <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group">
      <label>Contenu</label>
      <textarea name="content" class="form-control" cols="30" rows="10" id="markdown-textarea" placeholder="Contenu de l'article.."></textarea>
    </div>

    <button type="submit" class="btn btn-default">Créer</button>

  </form>

<% end %>

app/views/admin/manage_categories.html.erb
<% content_for :content do %>

  <h1>Gérer les Catégories</h1>
  <% if flash[:msg] %>
    <div class="alert alert-success"><%= flash[:msg] %></div>
  <% end %>
  <table class="table table-hover" style="margin: 40px 0;">
    <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody id="comments">
    <% @categories.each do |cat| %>
      <tr>
        <th><%= cat.name %></th>
        <th><a href="<%= categories_destroy_path(cat.id) %>?redirect=/admin/categories" class="btn btn-danger">Supprimer</a></th>
      </tr>
    <% end %>
    </tbody>
  </table>

<% end %>

app/views/admin/manage_comments.html.erb
<% content_for :content do %>

  <h1>Gérer les commentaires <button id="refresh-comment" class="btn btn-default">Rafraichir</button></h1>
  <% if flash[:msg] %>
  <div class="alert alert-success" id="commentSuccess"><%= flash[:msg] %></div>
  <% end %>
  <table class="table table-hover" style="margin: 40px 0;">
    <thead>
    <tr>
      <th scope="col">Titre</th>
      <th scope="col">Posté le </th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody id="comments" data-url="<%= all_comments_path %>">
    <tr>
     <th>
      <div class="loader" style="margin-top: 20px;">
        <div class="loader__line"></div>
        <div class="loader__line"></div>
        <div class="loader__line"></div>
        <div class="loader__line"></div>
      </div>
    </th>
    </tr>
    </tbody>
  </table>

<% end %>

app/views/admin/manage_users.html.erb
<% content_for :content do %>

  <h1>Gérer les Utilisateurs</h1>
  <% if flash[:msg] %>
    <div class="alert alert-success"><%= flash[:msg] %></div>
  <% end %>
  <table class="table table-hover" style="margin: 40px 0;">
    <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody id="comments">
    <% @users.each do |user| %>
      <tr>
        <th style="color: <%= user.banned == 1 ? "red": 'black' %>;"><%= user.username %></th>
        <th style="color: <%= user.banned == 1 ? "red": 'black' %>;"><%= user.email %></th>
        <% unless user.id == session[:id] %>
          <th><a href="<%= ninja_path(user.id) %>" class="btn btn-success">Ninja !</a></th>
      <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>

<% end %>