config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#index", as: "home"
  # articles
  get "/posts", as: "posts_format", to: "posts#index"
  get "/post/:id", to: "posts#show"
  get "/article/:slug", to: "pages#show", as: "post_show"
  # comments
  post "/comment/new", to: "comments#create", as: "create_comment"
  get "/comment/:id/delete", as: "delete_comment", to: "comments#destroy"
  #user
  get "/user/:username", to: "users#show", as: "show_user"
  get "/connexion", to: "connect#index_login", as: "login"
  post "/connexion", to: "connect#login"
  #categories
  get "categorie/:name", to: "categories#show", as: "show_category"
  #others
  post "/nous-contactez", to: "contact#index", as: "footer_mail"
  get "/404", :to => "pages#index"
  get "/recherche", as: "search", to: "pages#search"
  get "/rss", as: 'rss', to: "rss#index"

  # administration
  scope "/admin" do
    get "/", as: "admin_home", to: "admin#index"
    post "/", as: "new_post", to: "posts#create"
    get "/commentaires", as: "comments_management", to: "admin#manage_comments"
    get "/all_comments", as: "all_comments", to: "admin#all_comments"
    get "/ninja/:id", as: "ninja", to: "admin#ninja"
    get "/users", as: "users_management", to: "admin#manage_users"
    get "/categories", as: "categories_management", to: "admin#manage_categories"
    get "/categories/:id/destroy", as: "categories_destroy", to: "categories#destroy"
  end

  # user profile
  scope "/profil" do
    get "/", as: "user_profile", to: "profiles#dashboard"
    get "/deconextion", as: "disconnect", to: "profiles#disconnect"
    get "/article/:id/edit", as: "edit_article", to: "profiles#edit_post"
    post "/article/edit/:id", as: "edit", to: "posts#edit"
    get "/article/:id/delete", as: "delete", to: "posts#destroy"
  end

end

app/views/shared/_header.html.erb
<header id="header">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 overflow">
        <div class="social-icons pull-right">
          <ul class="nav nav-pills">
            <li><a href="/rss" target="_blank"><i class="fa fa-rss"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-inverse" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a data-turbolinks="false" class="navbar-brand" href="<%= home_path %>">
          <h1><img src="https://www.bettshow.com/__resource/companyProfiles/6ACCB598-5056-B762-90FBD8967B0A498B-logo.png" alt="" style="width: 40px;">Technoblog</h1>
        </a>

      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= "active" if request.original_url == home_url%>" id="header-link"><a href="<%= home_path %>">Accueil</a></li>
          <li class="dropdown <%= "active" if controller_name == "categories" %>" id="header-link"><a href="#">Catégories <i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
              <% Category.all.each do |c| %>
                <li class="<%= "active" if params[:name] == c.name %>"><a style="width: 100%;margin: 0;padding: 10px 10px;" href="<%= show_category_path(c.name) %>"><%= c.name %></a></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
      <div class="search">
        <a href="<%= search_path %>"><i class="fa fa-search"></i></a>
      </div>
    </div>
  </div>
</header>

app/views/shared/_mainbar.html.erb
<section id="page-breadcrumb">
  <div class="vertical-center sun">
    <div class="container">
      <div class="row">
        <div class="action">
          <div class="col-sm-6">
            <h1 class="title">Technoblog</h1>
            <p>Blog lié aux nouvelles technologies</p>
          </div>
          <% if is_connect? %>
            <div class="col-sm-6" id="img-profile-container">
              <h5 style="display: inline-block;margin-top: 28px;margin-left: 220px;">Connecté en temps que <%= current_user.username %></h5>
              <div class="img-circle">
                <a href="<%= user_profile_path %>">
                  <img id="profile-image" src="<%= User.find(session[:id]).picture %>" alt="">
                </a>
              </div>
            </div>
          <% else %>
            <div class="col-sm-6" id="register-link-container">
              <a class="login-btn" href="<%= login_path %>">Se connecter</a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_sidebar-profile.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="<%= show_user_path(user.username) %>">
          <%= user.username %>
        </a>
      </li>
      <li>
        <a href="<%= user_profile_path %>">Mon profil</a>
      </li>
      <% if is_connect_and_admin? %>
      <li>
        <a data-turbolinks='false' href="<%= new_post_path %>">Nouvel article</a>
      </li>
      <% end %>
      <li>
        <a href="<%= disconnect_path %>">Me déconnecter</a>
      </li>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->
</div>

app/views/shared/_sidebar.html.erb
<div class="col-md-3 col-sm-5" data-margin-top="20" id="sidebar">
  <div class="sidebar blog-sidebar">
    <div class="sidebar-item recent">
      <h3>Derniers article</h3>
      <% Post.posted.limit(4).order("created_at DESC").each do |p| %>
        <div class="media">
          <div class="pull-left">
            <a href="#"><img style="width: 100px;" src="<%= p.thumbnail %>" alt=""></a>
          </div>
          <div class="media-body">
            <h4><a href="<%= post_show_path(p.slug) %>"><%= p.title %></a></h4>
            <p>Il y a <%= time_ago_in_words(p.created_at) %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="sidebar-item categories">
      <h3>Catégories</h3>
      <ul class="nav navbar-stacked">
        <% Category.all.each do |c| %>
          <li><a href="<%= show_category_path(c.name) %>"><%= c.name %> (<%= c.post.count %>)</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>