config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#index", as: "home"
  # articles
  get "/posts", as: "posts_format", to: "posts#index"
  get "/post/:id", to: "posts#show"
  get "/article/:slug", to: "pages#show", as: "post_show"
  # comments
  post "/comment/new", to: "comments#create", as: "create_comment"
  get "/comment/:id/delete", as: "delete_comment", to: "comments#destroy"
  #user
  get "/user/:username", to: "users#show", as: "show_user"
  get "/connexion", to: "connect#index_login", as: "login"
  post "/connexion", to: "connect#login"
  #categories
  get "categorie/:name", to: "categories#show", as: "show_category"
  #others
  post "/nous-contactez", to: "contact#index", as: "footer_mail"
  get "/404", :to => "pages#index"
  get "/recherche", as: "search", to: "pages#search"
  get "/rss", as: 'rss', to: "rss#index"

  # administration
  scope "/admin" do
    get "/", as: "admin_home", to: "admin#index"
    post "/", as: "new_post", to: "posts#create"
    get "/commentaires", as: "comments_management", to: "admin#manage_comments"
    get "/all_comments", as: "all_comments", to: "admin#all_comments"
    get "/ninja/:id", as: "ninja", to: "admin#ninja"
    get "/users", as: "users_management", to: "admin#manage_users"
    get "/categories", as: "categories_management", to: "admin#manage_categories"
    get "/categories/:id/destroy", as: "categories_destroy", to: "categories#destroy"
  end

  # user profile
  scope "/profil" do
    get "/", as: "user_profile", to: "profiles#dashboard"
    get "/deconextion", as: "disconnect", to: "profiles#disconnect"
    get "/article/:id/edit", as: "edit_article", to: "profiles#edit_post"
    post "/article/edit/:id", as: "edit", to: "posts#edit"
    get "/article/:id/delete", as: "delete", to: "posts#destroy"
  end

end

app/views/pages/404.html.erb
<% content_for :content do %>
  <div class="col-sm-12">
    <div class="text-center">
      <div class="bg-404">
        <div class="error-image">
          <img class="img-responsive" src="images/404.png" alt="">
        </div>
      </div>
      <h2>PAGE NOT FOUND</h2>
      <p>The page you are looking for might have been removed, had its name changed.</p>
      <a href="index.html" class="btn btn-error">RETURN TO THE HOMEPAGE</a>
      <div class="social-link">
        <span><a href="#"><i class="fa fa-facebook"></i></a></span>
        <span><a href="#"><i class="fa fa-twitter"></i></a></span>
        <span><a href="#"><i class="fa fa-google-plus"></i></a></span>
      </div>
    </div>
  </div>

<% end %>

app/views/pages/category.html.erb
<% content_for :title do "Technoblog - "+ "Catégorie #{@category.name}" if @category end %>
<% content_for :content do %>
  <% if @category %>
    <h1><%= @category.name %></h1>
    <% if @category.post.count <= 0 %>
      <h3>Aucun articles dans cette catégorie</h3>
    <% else %>
      <ul>
        <% @category.post.all.order("created_at DESC").each do |post| %>
          <li><a href="<%= post_show_path(post.slug) %>"><%= post.title %></a></li>
        <% end %>
      </ul>
    <% end %>
  <% else %>
    <h1>Il semblerait que cette catégorie soit invalide</h1>
  <% end %>
<% end %>

app/views/pages/index.html.erb
<% content_for :title do "Technoblog" end %>
<% content_for :content do %>
  <div class="row" id="post-all" data-ajax="<%= posts_format_path %>.json" data-url="<%= home_url %>">
    <% if flash[:msg] %>
    <div class="alert alert-success"><%= flash[:msg] %></div>
    <% end %>
   <!-- rendering posts from javascript -->
    <div id="loader-posts" style="width: 100%;height: 100%;padding: 10px;">
      <div class="loader">
        <div class="loader__line"></div>
        <div class="loader__line"></div>
        <div class="loader__line"></div>
        <div class="loader__line"></div>
      </div>
    </div>
    <div id="post-content-list">
      <% if Post.posted.count < 1 %>
        <h1>Aucun article a été trouvé...</h1>
      <% else %>
        <% @posts.each do |post| %> <div class="col-md-6 col-sm-12 blog-padding-right"> <div class="single-blog two-column"> <div class="post-thumb" style="width: 390.75px;height: 219.8px;overflow: hidden;"> <a href="<%= post_show_path(post.slug) %>"><img src="<%= post.thumbnail %>" class="img-responsive" alt="" style="width: 100%;height: 100%;"></a> <div class="post-overlay"> <span class="uppercase"><a href="javascript:void(0);"><%= post.created_at.day %><br /><small><%= post.created_at.month %></small></a></span> </div> </div> <div class="post-content overflow"> <h2 class="post-title bold"><a href="<%= post_show_path(post.slug) %>"><%= truncate(post.title, length: 35) %></a></h2> <h3 class="post-author"><a href="#">Posté par <%= post.user.username %></a></h3> <p><%= strip_tags(Markdown.new(truncate(post.content, length: 63)).to_html) %></p> <a href="<%= post_show_path(post.slug) %>" class="read-more">Lire la suite</a> <div class="post-bottom overflow"> <ul class="nav nav-justified post-nav"> <li><a href="<%= show_category_path(post.category.name) %>"><i class="fa fa-tag"></i><%= truncate(post.category.name, length: 12) %></a></li> <li><a href="#"><i class="fa fa-comments"></i><%= post.comment.count %></a></li> </ul> </div> </div> </div> </div> <% end %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/pages/search.html.erb
<% content_for :title do %>
  <% if @post.count <= 0 || !@q %>
    Aucun résultat <%= "pour #{@q}" if @q %>
  <% else %>
    Résultat<%= "s" if @posts.count > 1%> pour <%= @q %>
  <% end %>
<% end %>
<% content_for :content do %>
  <h1 style="margin-bottom: 20px;">Résultat<%= "s" if @post.count > 1 %> <%= "pour <strong>#{@q}</strong>".html_safe if @q %></h1>
  <form id="search-form" name="search-form" method="get" action="<%= search_path %>" style="margin: 30px 0;width: 100%;padding-right: 14px;" data-turboform>
    <div class="form-group">
      <input type="text" id="search-text" name="q" class="form-control" required="required" placeholder="Tapez un mot clé..">
    </div>
    <div class="form-group">
      <input type="submit" class="btn btn-submit" value="Rechercher">
    </div>
  </form>
  <% if @post.count >= 1 %>
    <div class="row">
      <% @post.each do |post| %>
        <div class="col-md-6 col-sm-12 blog-padding-right">
          <div class="single-blog two-column">
            <div class="post-thumb" style="width: 390.75px;height: 219.8px;overflow: hidden;">
              <a href="<%= post_show_path(post.slug) %>"><img src="<%= post.thumbnail %>" class="img-responsive" alt="" style="width: 100%;height: 100%;"></a>
              <div class="post-overlay">
                <span class="uppercase"><a href="javascript:void(0);"><%= post.created_at.day %><br /><small><%= post.created_at.month %></small></a></span>
              </div>
            </div>
            <div class="post-content overflow">
              <h2 class="post-title bold"><a href="<%= post_show_path(post.slug) %>"><%= truncate(post.title, length: 30) %></a></h2>
              <h3 class="post-author"><a href="#">Posté par <%= post.user.username %></a></h3>
              <p><%= truncate(strip_tags(Markdown.new(post.content).to_html), length: 56) %></p>
              <a href="<%= post_show_path(post.slug) %>" class="read-more">Lire la suite</a>
              <div class="post-bottom overflow">
                <ul class="nav nav-justified post-nav">
                  <li><a href="<%= show_category_path(post.category.name) %>"><i class="fa fa-tag"></i><%= truncate(post.category.name, length: 12) %></a></li>
                  <li><a href="#"><i class="fa fa-comments"></i><%= post.comment.count %></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>Aucun résultat</h3>
  <% end %>
<% end %>

app/views/pages/show.html.erb
<% content_for :title do "#{@post.title} - Technoblog" end %>
<% content_for :content do %>
  <% if flash[:msg] %>
    <div class="alert alert-success">
      <%= flash[:msg] %>
    </div>
  <% end %>
  <div class="img-post" style="width: 100%;height: 400px;">
    <img data-toggle="tooltip" data-placement="top" title="Tooltip on top" src="<%= @post.thumbnail %>" alt="" style="width: 80%;height: 100%;">
  </div>
  <h1 style="background: #fff;transform: translateY(-60px);padding: 20px 10px 0 0;width: 70%;"><%= @post.title %><span style="margin-left: 20px;" class="badge badge-info"><a style="color: #fff" href="<%= show_category_path(@post.category.name) %>"><%= @post.category.name %></a></span></h1>
  <% if is_connect? && @post.user_id == session[:id] %>
  <a style="margin-top: -80px;" href="<%= edit_article_path(@post.id) %>" class="btn btn-primary" data-turbolinks="false">Éditer</a>
  <% end %>
  <p><a href="<%= show_user_path(@post.user.username) %>">Posté par <%= @post.user.username %> Le <%= @post.created_at.strftime("%F") %></a></p>
  <div id="post-content"><p style="font-size: 16px;"><%= raw simple_format(Markdown.new(@post.content).to_html, disable_indented_code_blocks: false) %></p></div>
  <div class="comments-post" style="margin-top: 60px;">
    <div class="title" style="width: 100%;padding-bottom: 10px;border-bottom: 1px solid #ebebeb;">
      <h2>Commentaires - <%= @post.comment.count %></h2>
    </div>
    <% if @post.comment.count < 1 %>
      <h3>Aucun commentaire</h3>
      <% if is_connect? %>
        <button class="btn btn-success" style="margin: 20px 0;" id="comment-button">Ajouter un commentaire</button>
        <form action="<%= create_comment_path %>" method="post" id="comment-form">
          <div class="form-group">
            <textarea name="content" class="form-control" cols="30" rows="3" placeholder="Votre commentaire"></textarea>
          </div>
          <input type="hidden" name="post" value="<%= @post.id %>">
          <button type="submit" class="btn btn-block">Envoyer</button>
        </form>
      <% else %>
      <div class="alert alert-warning">
        Veuillez vous connecter ou vous inscrire pour ajouter un commentaire.
      </div>
      <% end %>
    <% else %>
      <% if is_connect? %>
        <button class="btn btn-success" id="comment-button" style="margin: 20px 0;">Ajouter un commentaire</button>
        <form action="<%= create_comment_path %>" method="post" id="comment-form">
          <div class="form-group">
            <textarea name="content" class="form-control" cols="30" rows="5" placeholder="Votre commentaire"></textarea>
          </div>
          <input type="hidden" name="post" value="<%= @post.id %>">
          <button type="submit" class="btn btn-block">Envoyer</button>
        </form>
      <% else %>
        <div class="alert alert-warning">
          Veuillez vous connecter ou vous inscrire pour ajouter un commentaire.
        </div>
      <% end %>
      <% @post.comment.order("created_at DESC").each do |comment| %>
          <div class="comment" style="width: 100%;border-bottom: 1px solid #ebebeb">
            <div class="media" style="width: 20%;height: 100%;display: inline-block;float: left;padding: 30px 0;">
              <img src="<%= comment.user.picture %>" alt="<%= comment.user.username %>" style="width: 70%; height: 100%;">
              <p style="margin: 20px 0 0 0;padding: 0;"><a style="margin: 0;padding: 0;" href="javascript:void(0);">Il y a <%= time_ago_in_words(comment.created_at) %></a></p>
            </div>
            <div class="content" style="width: 80%;padding: 30px 0;display: inline-block;float: left;">
              <p style="margin: 0;padding: 0;"><a href="<%= show_user_path(comment.user.username) %>"><%= comment.user.username %></a></p>
              <p style="margin: 0;padding: 0;"><%= raw Markdown.new(comment.content).to_html %></p>
            </div>
            <div class="clear" style="clear: both"></div>
          </div>
      <% end %>
    <% end %>
  </div>
  <div class="buttons" style="margin-bottom: 120px;margin-top: 40px;width: 100%;">
    <% if @last %>
      <a class="btn btn-info wow bounceIn" style="float: left;" href="<%= post_show_path(@last.slug) %>"><i style="margin-right: 10px;" class="fa fa-arrow-left"></i><%= @last.title %></a>
    <% end %>
    <% if @next %>
      <a class="btn btn-info wow bounceIn" style="float: right;" href="<%= post_show_path(@next.slug) %>"><i style="margin-right: 10px;" class="fa fa-arrow-right"></i><%= @next.title %></a>
    <% end %>
  </div>
<% end %>